### PR TITLE
Added additional dict operators

### PR DESCRIPTION
**Pull request by Dutcher**

### CODE REVIEW

**Review by jgrandelli — CHANGES_REQUESTED** [review]
any tests???

**Review by codecaffeine — CHANGES_REQUESTED** [review]
++ on tests

**Comment by Dutcher** [comment]
Added unit tests

**Comment by jgrandelli** [comment]
Failing?

**Comment by jgrandelli** [comment]
Looks like you might just need to re-run it

**Review by jgrandelli — APPROVED** [review]

**Review by codecaffeine — APPROVED** [review]

**Comment by codecaffeine** [comment]
Ignoring the one Travis error

**Pull request merged**
