### PR TITLE
Fixes compiling issue with Xcode 8.3

### PR DESCRIPTION
**Pull request by codecaffeine**
URBNWhiteLabels tests were run on both Xcode 8.3 and Xcode 8.2 and everything passed

### CODE REVIEW

**Comment by flippinjoe** [comment]
I think you need to update the .travis.yml for 8.3

**Comment by codecaffeine** [comment]
🤔 it should still work with Xcode 8.2 _(tested on 8.2.1)_

**Comment by codecaffeine** [comment]
This doesn’t seem right:

```
xcodebuild: error: SDK "iphonesimulator10.0" cannot be located.
```

**Comment by flippinjoe** [comment]
`A build only device cannot be used to run this target.`

**Comment by codecaffeine** [comment]
This is stupid

**Comment by codecaffeine** [comment]
hate travis

**Pull request merged**
